matcher:
  KDTreeMatcher:
    knn: 3
    maxDist: 2.0
    epsilon: 1


outlierFilters:
 - TrimmedDistOutlierFilter:
    ratio: 0.7


errorMinimizer:
  PointToPlaneErrorMinimizer:


transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 2
  - CounterTransformationChecker:
      maxIterationCount: 40
  - BoundTransformationChecker:
      maxRotationNorm: 1.1
      maxTranslationNorm: 15.00

inspector:
  NullInspector

logger:
  NullLogger
